name: Sync beta to main

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  sync:
    name: Sync beta to main

    strategy:
      matrix:
        node-version: [18]
        os: [ubuntu-latest]

    runs-on: {{ matrix.os }}

    # Only run this job if the pull request is merged and the base branch is 'changeset-release/main', or if manually triggered
    if: ${{ (github.event.pull_request.merged == true && github.head_ref == 'changeset-release/main') || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: beta
          fetch-depth: 0

      - name: Install Changeset
        run: npm install -g @changesets/cli

      - name: Rebase beta on main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git stash save "Temporary stash before rebase"
          git fetch origin main
          git rebase origin/main
          git stash list | grep -q 'Temporary stash before rebase' && git stash apply --index || true


      # force enter prerelease mode for beta
      - name: Enter pre-release mode for Beta
        run: |
          if [ ! -f .changeset/pre.json ]; then
            npx changeset pre enter beta
          fi

      - name: Push beta to origin
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
        run: |

          git add .changeset/pre.json
          git commit -m "Enter pre-release mode" || true
          git push origin beta --force
